siteFacebookUrl = 'https://www.facebook.com/kniknistudio/'
siteVimeoUrl = 'https://vimeo.com/channels/kniknistudio'
siteInstagramUrl = 'https://www.instagram.com/knikni_studio/'
siteDribbleUrl = 'https://dribbble.com/kniknistudio'

